# -*- encoding: utf-8 -*-
# stub: diatheke 0.1.2 ruby lib
#
# This file is automatic generated by rim.
# PLEASE DO NOT EDIT IT DIRECTLY!
# Change instead the values in Rim.setup in Rakefile.

Gem::Specification.new do |s|
  s.name = "diatheke".freeze
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Jan Friedrich".freeze]
  s.date = "2016-02-08"
  s.description = "".freeze
  s.email = "janfri26@gmail.com".freeze
  s.files = ["COPYING".freeze, "Changelog".freeze, "README.md".freeze, "Rakefile".freeze, "lib/diatheke.rb".freeze, "test/test_diatheke.rb".freeze]
  s.rubygems_version = "2.5.2".freeze
  s.summary = "This library is a wrapper of the diatheke command-line client of the sword project.".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rim>.freeze, ["~> 2.6"])
    else
      s.add_dependency(%q<rim>.freeze, ["~> 2.6"])
    end
  else
    s.add_dependency(%q<rim>.freeze, ["~> 2.6"])
  end
end
