# -*- encoding: utf-8 -*-
# stub: diatheke 0.2.2 ruby lib
#
# This file is automatically generated by rim.
# PLEASE DO NOT EDIT IT DIRECTLY!
# Change the values in Rim.setup in Rakefile instead.

Gem::Specification.new do |s|
  s.name = "diatheke"
  s.version = "0.2.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Jan Friedrich"]
  s.date = "2020-01-03"
  s.description = ""
  s.email = "janfri26@gmail.com"
  s.files = ["COPYING", "Changelog", "README.md", "Rakefile", "diatheke.gemspec", "lib/diatheke.rb", "test/test_diatheke.rb"]
  s.rubygems_version = "3.1.2"
  s.summary = "This library is a wrapper of the diatheke command-line client of the sword project."

  if s.respond_to? :specification_version then
    s.specification_version = 4
  end

  if s.respond_to? :add_runtime_dependency then
    s.add_development_dependency(%q<rake>, [">= 0"])
    s.add_development_dependency(%q<rim>, ["~> 2.17"])
  else
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<rim>, ["~> 2.17"])
  end
end
