# -*- encoding: utf-8 -*-
# stub: diatheke 0.2.0 ruby lib
#
# This file is automatically generated by rim.
# PLEASE DO NOT EDIT IT DIRECTLY!
# Change the values in Rim.setup in Rakefile instead.

Gem::Specification.new do |s|
  s.name = "diatheke"
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Jan Friedrich"]
  s.date = "2017-08-15"
  s.description = ""
  s.email = "janfri26@gmail.com"
  s.files = ["COPYING", "Changelog", "README.md", "Rakefile", "lib/diatheke.rb", "test/test_diatheke.rb"]
  s.rubygems_version = "2.6.12"
  s.summary = "This library is a wrapper of the diatheke command-line client of the sword project."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rim>, ["~> 2.10"])
    else
      s.add_dependency(%q<rim>, ["~> 2.10"])
    end
  else
    s.add_dependency(%q<rim>, ["~> 2.10"])
  end
end
